### ISSUE TITLE
Customizar UI do Netlify CMS para page builder (2)

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront-cms#12]
> Fine-tuning após https://github.com/ecomplus/storefront-cms/issues/2

- [x] Acredito que a coluna de edição (quando há preview) pode ser ainda menor (talvez aqui seja só uma opinião);

- [x] O _adicionar_ para [_List Widget: Variable Types_](https://www.netlifycms.org/docs/beta-features/#list-widget-variable-types) deveria abir um dropdown com **as opções em grid** (ou pelo menos uma lista com largura maior), idealmente cada opção também deve poder ter um ícone:

> como está atualmente:
![Screen Shot 2022-01-03 at 14 58 29](https://user-images.githubusercontent.com/10326572/147964495-7dde0c07-9977-4e30-9fc0-f0b92b209bf5.png)

> ideal:
![57b3d74d01ecaa4ed324d5d3097f0c7e11eaf1d3](https://user-images.githubusercontent.com/10326572/147964576-4349878e-9aa1-4b28-82b4-ddc0ea535022.png)

- [x] Ainda temos muitas bordas aninhadas e espaço em branco no topo quando editamos uma seção, conseguimos deixar isso mais próximo do que ocorre no TinaCMS?

> atual:
![Screenshot 2022-01-03 at 15-12-51 My Shop](https://user-images.githubusercontent.com/10326572/147964879-52321817-9dd4-43de-a8c1-cefba55eeed4.png)

> ideal sem tantas bordas estranhas e espaço inutilizado, a única referência ao elemento parente é o header com o título e a seta para voltar a editá-lo:
![Screenshot 2021-12-20 at 20-00-41 Build contextual editing into your site](https://user-images.githubusercontent.com/10326572/146843967-44809d68-edc2-49a6-8251-a9037c4f864c.png)

**Comment by oscargross** [comment]
PR [https://github.com/ecomplus/storefront-cms/pull/15](url)

Ajustes de espaçamentos, adição de icones no dropdown, bug do botão back para listas e listas inside outras

https://user-images.githubusercontent.com/55117353/148385885-786e105e-857e-4c4e-9b3b-7dd539efd259.mp4


Uploading Netlify CMS Development Test - Google Chrome 2022-01-06 09-54-56.mp4…
![Screenshot_4](https://user-images.githubusercontent.com/55117353/148386231-bdbfd764-c443-43f0-9726-07ea3bf79c8c.png)

**Comment by oscargross** [comment]
https://user-images.githubusercontent.com/55117353/148386372-d7af154b-3030-4ef1-bb38-355eae8be3bc.mp4

**Comment by leomp12** [comment]
@oscargross nos vídeos eu vi campos com rich text editor e a toolbar ficou muito muito estranha quebrando todos os botões em várias linhas, não?
Talvez a coluna tenha que ficar um pouco mais larga mesmo pra ficar no máximo assim a toolbar:

![Screenshot 2022-01-06 at 13-19-40 My Shop](https://user-images.githubusercontent.com/10326572/148414711-48751529-112a-4234-aa31-dd07d51b4ff6.png)

Ou removemos essa opção "markdown" abrindo mais espaço horizontal na toolbar pros botões...

**Comment by leomp12** [comment]
> Ou removemos essa opção "markdown" abrindo mais espaço horizontal na toolbar pros botões...

Acho que essa opção é boa até.

**Comment by oscargross** [comment]
@leomp12 No ultimo ajuste ficou assim:
![image](https://user-images.githubusercontent.com/55117353/148430335-24335bb5-290c-49b1-b3de-f3652e7954b1.png)

**Comment by leomp12** [comment]
@oscargross boa!
