### ISSUE TITLE
Definir view da lista de entradas de file collections

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront-cms#13]
> Relacionado a https://github.com/ecomplus/storefront-cms/issues/4

Pra fazer valer os novos thumbnails, devemos poder configurar na collection a opção pela visualização em grid em vez do default lista.

> OU fazemos a thumbnail também aparecer na view de lista (acho que tende a ficar ruim 😬 )

**Comment by oscargross** [comment]
PR [https://github.com/ecomplus/storefront-cms/pull/14]
![Screenshot_2](https://user-images.githubusercontent.com/55117353/148276457-2b427f87-45b3-4f0b-a99c-b0d909d9e4c1.png)
![Screenshot_3](https://user-images.githubusercontent.com/55117353/148276463-127e6772-5753-4e52-87ee-565fa5505514.png)
