### ISSUE TITLE
Minors no rich text editor

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront-cms#16]
Não precisamos do _Code block_ no + do rich text editor, seria mais útil não ter esse + e em vez disso ter apenas um botão direto para adicionar imagem com [um ícone respectivo](https://icones.js.org/collection/all?s=image):

```html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--mdi" width="32" height="32" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M8.5 13.498l2.5 3.006l3.5-4.506l4.5 6H5m16 1v-14a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2z" fill="currentColor"></path></svg>
```

Além disso, no rich text editor _Image_ não é traduzido para _Imagem_ 😬 (aí talvez seja só faltando no [i18n](https://github.com/ecomplus/storefront-cms/blob/main/netlify-cms%402/packages/netlify-cms-core/src/lib/i18n.ts)...)

**Comment by leomp12** [comment]
![Screenshot 2022-01-06 at 23-38-16 My Shop](https://user-images.githubusercontent.com/10326572/148483262-34c13a0e-13e6-4332-ba8e-a0dbbe88f8e5.png)

**Comment by oscargross** [comment]
@leomp12 
PR [https://github.com/ecomplus/storefront-cms/pull/18]

Não possui mais dropdown nesse botão... adiciona direto o campo imagem
Testa por favor a legenda se fica certo agr, aqui não consegui testar direito isso 😬

![image](https://user-images.githubusercontent.com/55117353/148591524-305ea847-8401-4dbd-b159-a84aee7bf79b.png)

**Comment by leomp12** [comment]
boa, vou testar

**Comment by leomp12** [comment]
no hover do icon na toolbar funcionou, mas dentro do "textarea" continua _Image_:

![Screenshot 2022-01-07 at 18-24-21 My Shop](https://user-images.githubusercontent.com/10326572/148609436-a80a4e44-9feb-4e40-96ae-8fabd3fabbc8.png)

de qualquer forma já ficou bem melhor o rich text editor assim, sem o + e sem o toggle do markdown lá 👍🏾

**Comment by leomp12** [comment]
> mas dentro do "textarea" continua Image

tô mantendo aberto por isso, mas é bem minor também então vou deixar a seu critério...
esse https://github.com/ecomplus/storefront-cms/issues/17 é mais importante, aí já dou um release beta e vou separando os ícones e thumbnails aqui e botamos isso em prod

**Comment by oscargross** [comment]
@leomp12 não localizei onde colocar essa correção de texto 😓
A primeira correção foi nesse arquivo, mas não sei onde colocar pra corrigir dentro do corpo ("text-area")

[https://github.com/ecomplus/storefront-cms/blob/main/netlify-cms%402/packages/netlify-cms-locales/src/pt/index.js#:~:text=markdown%3A%20%27Markdown%27%2C-,image%3A%20%27Imagem%27,-%7D%2C](url)

**Comment by leomp12** [comment]
@oscargross o link que você colocou aí não rolou pra mim não man, mas fechamos assim mesmo por enquanto...

**Comment by oscargross** [comment]
@leomp12 estranho, mas se copiar e colar a url da certo 🤔

**Comment by leomp12** [comment]
você diz configurar a imagem por url em vez de upload @oscargross ?

**Comment by oscargross** [comment]
não não hahhah @leomp12 
Do link que não conseguiu abrir, se copiar ela e colar na barra de pesquisa, vai

**Comment by leomp12** [comment]
ahh entendi 😬
