### ISSUE TITLE
Minor pro "List widgets: variable types" ficar perfeito agora 😄 

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront-cms#17]
Ficou ótimo com as opções a adicionar em grid com ícones configuráveis! MAS.. 😛 

![Screenshot 2022-01-06 at 23-38-40 My Shop](https://user-images.githubusercontent.com/10326572/148483226-2b31f746-d5f7-4183-b368-3d439003f8ed.png)

Como as seções têm nomes grandes a string foi abreviada, até aí tudo bem mas o no hover o título também não aparece inteiro, talvez baste adicionar uma `title` tag exibindo a string toda.
Fora isso acho que essa fonte pode ser um pouco menor aí, principalmente considerando que vamos adicionar ícones pra cada opção, testei 13px e pareceu OK, assim também daria pra aumentar o máximo de chars antes de truncar a string.

**Comment by oscargross** [comment]
@leomp12 PR [https://github.com/ecomplus/storefront-cms/pull/19]

Haha vdd, agr fica abreviado um pouco maior, e toda a string com hover

https://user-images.githubusercontent.com/55117353/148656149-7bc77449-304b-4524-9406-52ea1d33af1d.mp4
