### ISSUE TITLE
Customizar UI do Netlify CMS para page builder

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront-cms#2]
Sendo um CMS de uso genérico, a UI do Netlify CMS não é tão amigável para o nosso usário final, principalmente como _page builder_, a intenção aqui é melhorar essa UX em geral, especialmente nos React components relacionados ao [_List Widget: Variable Types_](https://www.netlifycms.org/docs/beta-features/#list-widget-variable-types), usado para criar o drag&drop de [seções](https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-template/template/js/netlify-cms/base-config/sections.js) nas páginas como a [home](https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-template/template/js/netlify-cms/base-config/collections/pages/home.js#L20-L25).

O resultado final deve ser algo parecido com as demos to [Tina](https://tina.io/).

1. [x] A coluna de edição (esquerda) deve ser menor, deixando mais espaço para o preview;
2. [x] As sections só aparecem juntas em umas lista simples, form de configuração é aberto um por vez;
3. [x] Botão _mais_ em destaque para adicionar outras sections;
4. [x] ... 🤔 

![Screenshot 2021-12-20 at 19-55-47 Build contextual editing into your site](https://user-images.githubusercontent.com/10326572/146843537-2dabebb0-51fe-4ede-b746-99cffecaab0b.png)
![Screenshot 2021-12-20 at 20-00-16 Build contextual editing into your site](https://user-images.githubusercontent.com/10326572/146843960-f77e7c6e-bbfc-4f1d-8638-a664cf54dd22.png)
![Screenshot 2021-12-20 at 20-00-41 Build contextual editing into your site](https://user-images.githubusercontent.com/10326572/146843967-44809d68-edc2-49a6-8251-a9037c4f864c.png)

> Talvez dê pra fazer isso (o básico pelo menos) com customização dos estilos dos componentes apenas.

**Comment by leomp12** [comment]
@ricardocici @joaovescudero

**Comment by leomp12** [comment]
> Em paralelo a isso os nossos [_custom previews_](https://www.netlifycms.org/docs/customization/) vão ser melhorados com alguns fixes, perf e implementação de seções que faltam em https://github.com/ecomplus/storefront/tree/master/%40ecomplus/storefront-template/template/js/netlify-cms/preview

**Comment by oscargross** [comment]
PR 
[https://github.com/ecomplus/storefront-cms/pull/3]
Nele foram alterados: botão add, dropdown, topbar, typedList e forma de representação de typedList aberto

**Comment by oscargross** [comment]
https://user-images.githubusercontent.com/55117353/147471771-d001995e-4358-43c7-8d97-43dc0714d718.mp4

**Comment by leomp12** [comment]
Boa @oscargross !
Acho que na frente do nome do _type_ a gente pode colocar um ícone que indique edição (🔧 , 🖊️ ...), o que acha?
E conseguiu forçar o `max-width` da coluna da esquerda? Idealmente só quando há preview...

**Comment by oscargross** [comment]
Show @leomp12  
PR [https://github.com/ecomplus/storefront-cms/pull/5]

Inserido max-width para SplitPane com preview e adição de ícones editar ao lado do nome das listas, como no exemplo do video (Typed 1 Object ... Typed 2 Object... )

**Comment by leomp12** [comment]
Só faltou o vídeo @oscargross haha

**Comment by oscargross** [comment]
Opa, agr sim
https://user-images.githubusercontent.com/55117353/147677460-ce7649a4-6946-47ff-abd6-836fbbb9fcf8.mp4
