### ISSUE TITLE
Botões para setar múltiplos fields

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront-cms#21]
Seria ótimo se conseguirmos criar botões que configuram automaticamente layouts diferentes e até alteram os banners padrão, para isso precisaríamos em uma única ação editar vários objetos das sections, que são configuradas pelo famigerado _List widgets: variable types_.

**Comment by leomp12** [comment]
Melhor ainda se conseguirmos em uma única ação editar mais de um file no output do CMS (`content`).

**Comment by oscargross** [comment]
Testes para deixar os fields dinâmicos na montagem de layouts, assim poderá feita a edição de vários files em um clique:

  1 - Pegar fields de outra prop do config, 'predefined'
  collection.get('predefined')
  irá retornar os fields do predefined, porém apenas pra edição, na montagem da loja irá puxar os fields padrão;

  2 - Setar fields com o .set()
  updateFieldByKey(collection, 'key', (newfield) => newfield)
  ou
  collection.set('predefined', collection.get('fields', List<EntryField>()))
  Não funcionou e a função é declarada para gerar componentes vazios, então teria que pensar outra forma;

3 - Criar outra collection só com os layouts e fields separados
Na config, porém a collection é passada em tds as solicitações e não consegui fazer puxar os fields de outra collection quando estou abrindo a primeira collection.
const fields = collection.get('fields').toArray();
Também será confuso na tela inicial (menu com collections em lista a esquerda), isolar a collection padrão dos layouts.

4 - Tranformar fields em array
Alterar em tds os locais que propriedades e fields são chamados para informar qual o indice na lista, ficando cada layout em uma posição. Novamente, todas as funções para pegar informações dos fields recebem a collection e não consegui puxar os campos dos fields na montagem da loja com eles estando em uma lista.
 predefined: 
      - { label: 'Markdown', name: 'markdown', widget: 'markdown' }
      - { label: 'Datetime', name: 'datetime', widget: 'datetime' }
    fields:
[
...
]

Não abri PR pois fiz esses testes isolados e um não podia interferir no outro..

Caso tenham mais alguma ideia pra teste, se não, abortar missão.🥵

**Comment by leomp12** [comment]
Tendi 😐 
Vamos só pelo admin mesmo então (pelo menos por enquanto), como conversamos naquela call.

**Comment by oscargross** [comment]
Feito o carreto

![image](https://user-images.githubusercontent.com/55117353/153003767-727b537e-ac65-4a88-805f-ee590ea98fa6.png)

**Comment by leomp12** [comment]
@oscargross 💪🏾 

<img src="https://media3.giphy.com/media/yoJC2GnSClbPOkV0eA/giphy.gif?cid=ecf05e47bbfcc27a40651639696a327506a1f9e0117fd1d0&rid=giphy.gif&ct=g">
