### ISSUE TITLE
Abrir novo objeto na lista automaticamente

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront-cms#22]
Quando adicionamos um objeto na lista ele não é aberto para configuração e isso pode deixar o usuário sem saber se a ação fez efeito ou não e como ele deve prosseguir, por exemplo:

![Screenshot 2022-01-29 at 04-18-50 My Shop](https://user-images.githubusercontent.com/10326572/151651749-f81a2972-6951-425e-91de-f4b6d3b60915.png)

Adicionando um slide ele deveria abrir automaticamente para configurar a imagem adicional, atualmente isso não acontece, só aparecendo essa entrada nova na lista com _No img_ 😬

**Comment by oscargross** [comment]
PR https://github.com/ecomplus/storefront-cms/pull/23

Adicionado texto para clicar caso não haja value no primeiro item da lista.. tamanho max de 30 caracteres, para não quebrar linha na lista e no botão back quando item está "aberto".

https://user-images.githubusercontent.com/55117353/151859084-706ad597-e724-4f2e-82a0-c04afd52933a.mp4

**Comment by leomp12** [comment]
https://github.com/ecomplus/storefront-cms/pull/23 não abriu automaticamente mas melhorou 99% , fica a seu critério, se ja quiser fechar ...

**Comment by oscargross** [comment]
Entendi, abrir o item que foi incluso fica meio ruim quando tem muitos fields nele... nos casos de querer ajustar a posição, deletar (se foi adicionado para teste) ou precisar verificar as outras listas, acabam ficando lá em baixo. 
Vou fechar, mas se ver que é crucial, eu vejo dnv kkk
