### ISSUE TITLE
Thumbs na lista de entradas de file collections

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront-cms#4]
https://www.netlifycms.org/docs/collection-types/#file-collections

No nosso caso seria útil para melhorar a UI da lista de widgets do Storefront:

![Screenshot 2021-12-27 at 20-20-24 My Shop](https://user-images.githubusercontent.com/10326572/147513177-88454821-88b8-4761-9804-257654c18add.png)

https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-template/template/js/netlify-cms/base-config/collections/widgets.js

A intenção é adicionar imagens (setadas na config do CMS) nesse espaço em branco dos cards, em geral serão logos dos apps integrados (eg.: Google Analytics).

Me parece relacionado ao componente [`GridCard`](https://github.com/ecomplus/storefront-cms/blob/main/netlify-cms%402/packages/netlify-cms-core/src/components/Collection/Entries/EntryCard.js#L112-L120).

> Talvez isso já seja possível pelo Netlify CMS e só não há um exemplo na documentação.

**Comment by oscargross** [comment]
PR [https://github.com/ecomplus/storefront-cms/pull/7]


![image](https://user-images.githubusercontent.com/55117353/147826343-5505ab68-5154-44cb-aafa-978071835ddf.png)
![image](https://user-images.githubusercontent.com/55117353/147826369-e8d706b9-1162-47cc-9613-4288229515cf.png)

**Comment by leomp12** [comment]
https://github.com/ecomplus/storefront-cms/commit/236af9c4a4d5f2695973619a43f5f5af8c79c18a
